### ISSUE TITLE
 led.stop() not working in repl

### ISSUE THREAD

**Issue by vkuehn** [AnnaGerber/node-ardx#36]
Hi,

thanks for the example . Is the project now dead ?

If not... I get with node  v7.6.0 only an object to console print when entering led.stop() after
node CIRC01-code-led-a-strobe.js. Any idea why ?

Thanks for any hint of a project succesor or problem sulution

V

**Comment by vkuehn** [comment]
no answer after Months...consider it a dead project

**Comment by AnnaGerber** [comment]
Sorry I didn't see the issue notification. 
I need to update the project dependencies to use the latest version johnny-five library

I'd suggest using the latest version of johnny-five and if also follow code examples here: http://johnny-five.io/examples/led/
